### ISSUE TITLE
Logo Proposal For Auto Permission Project

### ISSUE THREAD

**Issue by iqbalhood** [pedroSG94/AutoPermissions#2]
Hi I have contacted you a few days ago via email, Here is the logo I want to offer for your project.
#### Logo Offering
![permission](https://user-images.githubusercontent.com/1563756/41806808-a39c7e9c-76ee-11e8-9ccb-e9c933ec5b0d.jpeg)

#### Logo Concept

![b4f1c11a-3b87-4aec-8522-eb09ebb0f7f3](https://user-images.githubusercontent.com/1563756/41806809-b04981e4-76ee-11e8-8f7e-ad4820b45d52.jpeg)

 I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

**Comment by pedroSG94** [comment]
Nice! I like it :D. I don't need any type or size because AS resize it for me.
I added the icon to app and readme.
